/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BadsanierungRouteImport } from './routes/badsanierung'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EntruempelungIndexRouteImport } from './routes/entruempelung/index'
import { Route as EntruempelungAgbRouteImport } from './routes/entruempelung/agb'
import { Route as EntruempelungDatenschutzRouteImport } from './routes/entruempelung/datenschutz'
import { Route as EntruempelungImpressumRouteImport } from './routes/entruempelung/impressum'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BadsanierungRoute = BadsanierungRouteImport.update({
  id: '/badsanierung',
  path: '/badsanierung',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EntruempelungIndexRoute = EntruempelungIndexRouteImport.update({
  id: '/entruempelung/',
  path: '/entruempelung/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntruempelungAgbRoute = EntruempelungAgbRouteImport.update({
  id: '/entruempelung/agb',
  path: '/entruempelung/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const EntruempelungDatenschutzRoute =
  EntruempelungDatenschutzRouteImport.update({
    id: '/entruempelung/datenschutz',
    path: '/entruempelung/datenschutz',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntruempelungImpressumRoute = EntruempelungImpressumRouteImport.update({
  id: '/entruempelung/impressum',
  path: '/entruempelung/impressum',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badsanierung': typeof BadsanierungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/entruempelung/agb': typeof EntruempelungAgbRoute
  '/entruempelung/datenschutz': typeof EntruempelungDatenschutzRoute
  '/entruempelung/impressum': typeof EntruempelungImpressumRoute
  '/entruempelung/': typeof EntruempelungIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badsanierung': typeof BadsanierungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/entruempelung/agb': typeof EntruempelungAgbRoute
  '/entruempelung/datenschutz': typeof EntruempelungDatenschutzRoute
  '/entruempelung/impressum': typeof EntruempelungImpressumRoute
  '/entruempelung': typeof EntruempelungIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badsanierung': typeof BadsanierungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/entruempelung/agb': typeof EntruempelungAgbRoute
  '/entruempelung/datenschutz': typeof EntruempelungDatenschutzRoute
  '/entruempelung/impressum': typeof EntruempelungImpressumRoute
  '/entruempelung/': typeof EntruempelungIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badsanierung'
    | '/sitemap.xml'
    | '/entruempelung/agb'
    | '/entruempelung/datenschutz'
    | '/entruempelung/impressum'
    | '/entruempelung/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badsanierung'
    | '/sitemap.xml'
    | '/entruempelung/agb'
    | '/entruempelung/datenschutz'
    | '/entruempelung/impressum'
    | '/entruempelung'
  id:
    | '__root__'
    | '/'
    | '/badsanierung'
    | '/sitemap.xml'
    | '/entruempelung/agb'
    | '/entruempelung/datenschutz'
    | '/entruempelung/impressum'
    | '/entruempelung/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadsanierungRoute: typeof BadsanierungRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EntruempelungAgbRoute: typeof EntruempelungAgbRoute
  EntruempelungDatenschutzRoute: typeof EntruempelungDatenschutzRoute
  EntruempelungImpressumRoute: typeof EntruempelungImpressumRoute
  EntruempelungIndexRoute: typeof EntruempelungIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badsanierung': {
      id: '/badsanierung'
      path: '/badsanierung'
      fullPath: '/badsanierung'
      preLoaderRoute: typeof BadsanierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entruempelung/': {
      id: '/entruempelung/'
      path: '/entruempelung'
      fullPath: '/entruempelung/'
      preLoaderRoute: typeof EntruempelungIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entruempelung/agb': {
      id: '/entruempelung/agb'
      path: '/entruempelung/agb'
      fullPath: '/entruempelung/agb'
      preLoaderRoute: typeof EntruempelungAgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entruempelung/datenschutz': {
      id: '/entruempelung/datenschutz'
      path: '/entruempelung/datenschutz'
      fullPath: '/entruempelung/datenschutz'
      preLoaderRoute: typeof EntruempelungDatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entruempelung/impressum': {
      id: '/entruempelung/impressum'
      path: '/entruempelung/impressum'
      fullPath: '/entruempelung/impressum'
      preLoaderRoute: typeof EntruempelungImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadsanierungRoute: BadsanierungRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EntruempelungAgbRoute: EntruempelungAgbRoute,
  EntruempelungDatenschutzRoute: EntruempelungDatenschutzRoute,
  EntruempelungImpressumRoute: EntruempelungImpressumRoute,
  EntruempelungIndexRoute: EntruempelungIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
