/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as BadsanierungRouteImport } from './routes/badsanierung'
import { Route as BodenverlegungRouteImport } from './routes/bodenverlegung'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EntruempelungIndexRouteImport } from './routes/entruempelung/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const BadsanierungRoute = BadsanierungRouteImport.update({
  id: '/badsanierung',
  path: '/badsanierung',
  getParentRoute: () => rootRouteImport,
} as any)
const BodenverlegungRoute = BodenverlegungRouteImport.update({
  id: '/bodenverlegung',
  path: '/bodenverlegung',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EntruempelungIndexRoute = EntruempelungIndexRouteImport.update({
  id: '/entruempelung/',
  path: '/entruempelung/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/badsanierung': typeof BadsanierungRoute
  '/bodenverlegung': typeof BodenverlegungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/entruempelung/': typeof EntruempelungIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/badsanierung': typeof BadsanierungRoute
  '/bodenverlegung': typeof BodenverlegungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/entruempelung': typeof EntruempelungIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/badsanierung': typeof BadsanierungRoute
  '/bodenverlegung': typeof BodenverlegungRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/entruempelung/': typeof EntruempelungIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/badsanierung'
    | '/bodenverlegung'
    | '/datenschutz'
    | '/impressum'
    | '/sitemap.xml'
    | '/entruempelung/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/badsanierung'
    | '/bodenverlegung'
    | '/datenschutz'
    | '/impressum'
    | '/sitemap.xml'
    | '/entruempelung'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/badsanierung'
    | '/bodenverlegung'
    | '/datenschutz'
    | '/impressum'
    | '/sitemap.xml'
    | '/entruempelung/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  BadsanierungRoute: typeof BadsanierungRoute
  BodenverlegungRoute: typeof BodenverlegungRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EntruempelungIndexRoute: typeof EntruempelungIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badsanierung': {
      id: '/badsanierung'
      path: '/badsanierung'
      fullPath: '/badsanierung'
      preLoaderRoute: typeof BadsanierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bodenverlegung': {
      id: '/bodenverlegung'
      path: '/bodenverlegung'
      fullPath: '/bodenverlegung'
      preLoaderRoute: typeof BodenverlegungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entruempelung/': {
      id: '/entruempelung/'
      path: '/entruempelung'
      fullPath: '/entruempelung/'
      preLoaderRoute: typeof EntruempelungIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  BadsanierungRoute: BadsanierungRoute,
  BodenverlegungRoute: BodenverlegungRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EntruempelungIndexRoute: EntruempelungIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
